# spring:
#   application:
#     name: fintech
# /src/main/resources/application.yml
spring:
  r2dbc:
    url: r2dbc:h2:mem:///fintechdb
    username: sa
    password:

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
